"""Vercel — auth-injecting passthrough to the official `vercel` CLI.

The npm `vercel` binary ships in the sandbox image (pinned via
`VERCEL_CLI_VERSION` in services/sandbox/Dockerfile). This tool does not
reimplement that CLI's surface; it resolves the `VERCEL_TOKEN` placeholder,
appends `--token` when the caller did not pass one, and delegates. iron-proxy
swaps the placeholder for the real credential on requests to `api.vercel.com`,
so the sandbox never holds the token.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

# Matches GENERATED_SHIM_MARKER in services/sandbox/install_tool_shims.py.
# The first `vercel` on PATH is usually this tool's own shim; skip it when
# resolving the real binary so the wrapper cannot recurse into itself.
_SHIM_MARKER = b"generated by install-tool-shims"

_TOKEN_FLAGS = ("--token", "-t")
_DEFAULT_TIMEOUT_SECONDS = 300


def _is_tool_shim(path: Path) -> bool:
    try:
        return _SHIM_MARKER in path.read_bytes()[:512]
    except OSError:
        return False


def vercel_binary() -> str:
    """Locate the npm-installed `vercel` binary, skipping this tool's own shim."""
    # PATH is not a secret; TID251 guards secret reads only.
    for entry in os.environ.get("PATH", "").split(os.pathsep):  # noqa: TID251
        candidate = Path(entry or ".") / "vercel"
        if candidate.is_file() and os.access(candidate, os.X_OK) and not _is_tool_shim(candidate):
            return str(candidate)
    raise FileNotFoundError(
        "vercel binary not found on PATH; the sandbox image installs it "
        "(VERCEL_CLI_VERSION in services/sandbox/Dockerfile)"
    )


def with_token(args: list[str]) -> list[str]:
    """Return CLI args with `--token <placeholder>` appended unless the caller passed one."""
    if any(arg in _TOKEN_FLAGS or arg.startswith("--token=") for arg in args):
        return list(args)
    from centaur_sdk.tool_sdk import secret

    # Replace-mode HTTP secrets resolve to the placeholder (the secret name
    # itself) unless a real value is configured in a local .env; either way the
    # string is safe to place on the command line.
    token = secret("VERCEL_TOKEN", "VERCEL_TOKEN")
    return [*args, "--token", token]


class VercelClient:
    """Thin subprocess wrapper for workflow `ctx.call_tool(...)` use.

    Interactive use should go through the `vercel` CLI shim, which execs the
    real binary and preserves streaming output and prompts.
    """

    def run(self, args: list[str], timeout: int = _DEFAULT_TIMEOUT_SECONDS) -> dict:
        """Run a vercel CLI command; returns exit_code, stdout, stderr."""
        result = subprocess.run(
            [vercel_binary(), *with_token(list(args))],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return {
            "exit_code": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr,
        }

    def whoami(self) -> dict:
        """Current authenticated user — a safe connectivity and auth check."""
        return self.run(["whoami"])

    def list_projects(self) -> dict:
        """Projects for the authenticated scope."""
        return self.run(["project", "ls"])

    def list_deployments(self, project: str | None = None) -> dict:
        """Recent deployments, optionally scoped to one project."""
        args = ["ls"]
        if project:
            args.append(project)
        return self.run(args)

    def deployment_logs(self, deployment: str) -> dict:
        """Build logs for a deployment URL or id.

        Uses `inspect --logs`, which prints and exits. Runtime log *streaming*
        (`vercel logs`) follows until interrupted, so it suits the interactive
        CLI shim rather than this non-interactive method.
        """
        return self.run(["inspect", deployment, "--logs"])


def _client() -> VercelClient:
    return VercelClient()
