from __future__ import annotations

import importlib.util
import sys
import types
from pathlib import Path

spec = importlib.util.spec_from_file_location(
    "vercel_client", Path(__file__).with_name("client.py")
)
assert spec and spec.loader
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)


def _stub_secret(monkeypatch, value: str | None = None) -> None:
    """Provide a fake centaur_sdk.tool_sdk.secret for the lazy import in with_token."""
    tool_sdk = types.ModuleType("centaur_sdk.tool_sdk")
    tool_sdk.secret = lambda key, default=None: value if value is not None else (default or key)
    package = types.ModuleType("centaur_sdk")
    package.tool_sdk = tool_sdk
    monkeypatch.setitem(sys.modules, "centaur_sdk", package)
    monkeypatch.setitem(sys.modules, "centaur_sdk.tool_sdk", tool_sdk)


def _write_executable(path: Path, content: str) -> None:
    path.write_text(content)
    path.chmod(0o755)


def test_with_token_appends_placeholder(monkeypatch) -> None:
    _stub_secret(monkeypatch)
    assert module.with_token(["ls"]) == ["ls", "--token", "VERCEL_TOKEN"]


def test_with_token_respects_explicit_token(monkeypatch) -> None:
    _stub_secret(monkeypatch)
    for args in (["ls", "--token", "abc"], ["ls", "--token=abc"], ["ls", "-t", "abc"]):
        assert module.with_token(args) == args


def test_vercel_binary_skips_own_shim(monkeypatch, tmp_path: Path) -> None:
    shim_dir = tmp_path / "shims"
    real_dir = tmp_path / "real"
    shim_dir.mkdir()
    real_dir.mkdir()
    _write_executable(
        shim_dir / "vercel",
        '#!/bin/sh\n# generated by install-tool-shims\nexec centaur-tools run vercel "$@"\n',
    )
    _write_executable(real_dir / "vercel", "#!/bin/sh\necho vercel\n")
    monkeypatch.setenv("PATH", f"{shim_dir}:{real_dir}")
    assert module.vercel_binary() == str(real_dir / "vercel")


def test_vercel_binary_missing_raises(monkeypatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PATH", str(tmp_path))
    try:
        module.vercel_binary()
    except FileNotFoundError as exc:
        assert "VERCEL_CLI_VERSION" in str(exc)
    else:
        raise AssertionError("expected FileNotFoundError")


def test_run_invokes_binary_with_token(monkeypatch) -> None:
    _stub_secret(monkeypatch)
    monkeypatch.setattr(module, "vercel_binary", lambda: "/usr/bin/vercel")
    calls: list[list[str]] = []

    def fake_run(argv, capture_output, text, timeout):
        calls.append(list(argv))
        return types.SimpleNamespace(returncode=0, stdout="ok\n", stderr="")

    monkeypatch.setattr(module.subprocess, "run", fake_run)
    result = module.VercelClient().whoami()
    assert result == {"exit_code": 0, "stdout": "ok\n", "stderr": ""}
    assert calls == [["/usr/bin/vercel", "whoami", "--token", "VERCEL_TOKEN"]]
