//! Workflow-owned button feedback using the runner's existing checkpoints.
use std::{
    future::Future,
    sync::{
        Arc,
        atomic::{AtomicBool, Ordering},
    },
};

use absurd::{StepHandle, TaskContext};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

use crate::WorkflowRuntimeError;

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ButtonFeedback {
    original: Value,
    processing: Value,
    #[serde(skip)]
    updated_step: Option<StepHandle<bool>>,
    #[serde(skip)]
    updated: Arc<AtomicBool>,
}

impl ButtonFeedback {
    /// Only render button rows generated by ctx.slack_buttons. The invocation
    /// must pass signature verification before this value is used.
    pub fn from_invocation(invocation: &crate::slack_buttons::Invocation) -> Option<Self> {
        let message = invocation.message.as_ref()?;
        let group_id = invocation.click["id"].as_str()?;
        let action = invocation.click["action"].as_str()?;
        let channel = invocation.click["channel_id"].as_str()?;
        let ts = invocation.click["message_ts"].as_str()?;
        let prefix = format!("centaur.workflow.action:{group_id}:");
        let action_id = format!("{prefix}{action}");
        let blocks = message["blocks"].as_array()?;
        let mut processing_blocks = blocks.clone();
        let index = blocks.iter().position(|block| {
            block["type"] == "actions"
                && block["elements"].as_array().is_some_and(|elements| {
                    elements.iter().all(|element| {
                        element["type"] == "button"
                            && element["action_id"]
                                .as_str()
                                .is_some_and(|id| id.starts_with(&prefix))
                    }) && elements.iter().any(|element| {
                        element["action_id"] == action_id && element["value"] == invocation.button
                    })
                })
        })?;
        let selected = blocks[index]["elements"]
            .as_array()?
            .iter()
            .find(|element| element["action_id"] == action_id)?;
        let label = selected["text"]["text"].as_str()?;
        let status = format!("⏳ {label}: Processing…");
        processing_blocks[index] = json!({
            "type": "context", "elements": [{"type": "plain_text", "text": status}]
        });
        let text = message["text"].as_str().unwrap_or_default();
        Some(Self {
            original: json!({"channel": channel, "ts": ts, "text": text, "blocks": blocks}),
            updated_step: None,
            updated: Arc::default(),
            processing: json!({"channel": channel, "ts": ts,
                "text": format!("{text}\n{status}"), "blocks": processing_blocks}),
        })
    }
}

/// Report update errors through the context RPC without losing a successful Slack edit.
pub(crate) async fn update(
    feedback: Option<&ButtonFeedback>,
    ctx: &TaskContext,
    message: &Value,
    response: impl Future<Output = Result<Value, WorkflowRuntimeError>>,
) -> Result<Value, String> {
    let value = response.await.map_err(|error| error.to_string())?;
    if let Some(feedback) = feedback
        && message["channel"] == feedback.original["channel"]
        && message["ts"] == feedback.original["ts"]
    {
        // Slack already changed. A checkpoint error must never let cleanup
        // overwrite that result, even when Python does not catch the RPC error.
        feedback.updated.store(true, Ordering::SeqCst);
        if let Some(step) = &feedback.updated_step {
            ctx.complete_step(step.clone(), true)
                .await
                .map_err(|error| error.to_string())?;
        }
    }
    Ok(value)
}

/// Keep feedback in the workflow's ordered execution, including retry/replay.
pub(crate) async fn run<T, SendFuture, HandlerFuture>(
    mut feedback: Option<ButtonFeedback>,
    ctx: &TaskContext,
    send: impl Fn(Value) -> SendFuture + Send + Sync,
    handler: impl FnOnce(Option<ButtonFeedback>) -> HandlerFuture,
) -> absurd::Result<T>
where
    SendFuture: Future<Output = Result<Value, WorkflowRuntimeError>> + Send,
    HandlerFuture: Future<Output = absurd::Result<T>>,
{
    let preparation = async {
        if let Some(feedback) = &mut feedback {
            let updated = ctx.begin_step::<bool>("$slack_button.updated").await?;
            feedback.updated.store(updated.done, Ordering::SeqCst);
            feedback.updated_step = Some(updated);
            if !feedback.updated.load(Ordering::SeqCst) {
                ctx.step(
                    &format!("$slack_button.processing:{}", ctx.attempt()),
                    || async {
                        send(feedback.processing.clone())
                            .await
                            .map_err(crate::absurd_error)
                    },
                )
                .await?;
            }
        }
        Ok::<_, absurd::Error>(())
    }
    .await;
    if let Err(error) = preparation {
        tracing::warn!(%error, "failed to prepare workflow button feedback");
        // Without reading the marker we cannot safely replace or restore a
        // message from a previous attempt. Continue without cosmetic edits.
        if feedback
            .as_ref()
            .is_some_and(|feedback| feedback.updated_step.is_none())
        {
            feedback = None;
        }
    }
    let result = handler(feedback.clone()).await;
    // Suspension still means work in progress. On rejection/failure, restore
    // only our own busy state; an explicit workflow edit owns the result.
    if !matches!(&result, Err(absurd::Error::Suspend))
        && let Some(feedback) = feedback
        && !feedback.updated.load(Ordering::SeqCst)
    {
        let restored = ctx
            .step(
                &format!("$slack_button.restore:{}", ctx.attempt()),
                || async {
                    send(feedback.original.clone())
                        .await
                        .map_err(crate::absurd_error)
                },
            )
            .await;
        if let Err(error) = restored {
            tracing::warn!(%error, "failed to restore workflow buttons");
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use absurd::{Client, ClientOptions, SpawnOptions, TaskResultSnapshot, WorkBatchOptions};
    use std::{sync::atomic::AtomicUsize, time::Duration};
    use tokio::sync::Mutex;

    fn fixture() -> ButtonFeedback {
        let id = "00000000-0000-0000-0000-000000000001";
        let mut message = json!({"channel": "C1", "text": "Approve release?", "blocks": [
            {"type": "section", "text": {"type": "mrkdwn", "text": "Approve release?"}},
            {"type": "actions", "elements": (["approve", "reject"].map(|action| json!({
                "type": "button", "text": {"type": "plain_text", "text": action},
                "action_id": format!("centaur.workflow.action:{id}:{action}"),
                "value": json!({"workflow_name": "review", "input": {}}).to_string()
            })))}
        ]});
        crate::slack_buttons::sign_message(&mut message, b"fixture-key").unwrap();
        let invocation = crate::slack_buttons::Invocation {
            button: message["blocks"][1]["elements"][0]["value"]
                .as_str()
                .unwrap()
                .into(),
            click: json!({"id": id, "action": "approve", "channel_id": "C1", "message_ts": "1.1"}),
            idempotency_key: "click-1".into(),
            message: Some(message),
        };
        ButtonFeedback::from_invocation(&invocation).unwrap()
    }

    #[test]
    fn busy_state_replaces_the_button_row_and_preserves_the_message() {
        let feedback = fixture();
        assert_eq!(
            feedback.processing["blocks"][0],
            feedback.original["blocks"][0]
        );
        assert_eq!(
            feedback.processing["blocks"][1],
            json!({"type": "context", "elements": [
                {"type": "plain_text", "text": "⏳ approve: Processing…"}
            ]})
        );
        assert_eq!(
            feedback.processing["text"],
            "Approve release?\n⏳ approve: Processing…"
        );
        assert_eq!(
            feedback.original["blocks"][1]["elements"]
                .as_array()
                .unwrap()
                .len(),
            2
        );
    }

    #[tokio::test]
    async fn durable_feedback_restores_rejection_and_failure_and_preserves_results_on_replay()
    -> Result<(), Box<dyn std::error::Error>> {
        let Ok(url) = std::env::var("SESSION_SQLX_TEST_DATABASE_URL")
            .or_else(|_| std::env::var("SESSION_RUNTIME_TEST_DATABASE_URL"))
            .or_else(|_| std::env::var("ABSURD_TEST_DATABASE_URL"))
        else {
            eprintln!("skipping button feedback tests: set SESSION_SQLX_TEST_DATABASE_URL");
            return Ok(());
        };
        let pool = sqlx::PgPool::connect(&url).await?;
        let installed: bool = sqlx::query_scalar(
            "SELECT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'absurd')",
        )
        .fetch_one(&pool)
        .await?;
        if !installed {
            sqlx::raw_sql(include_str!(
                "../../centaur-session-sqlx/migrations/0007_absurd_workflows.sql"
            ))
            .execute(&pool)
            .await?;
        }
        let client = Client::from_pool_with_options(
            pool,
            ClientOptions {
                queue_name: format!("button_{}", uuid::Uuid::new_v4().simple()),
                ..Default::default()
            },
        )?;
        client.create_queue(None, Default::default()).await?;
        let edits = Arc::new(Mutex::new(Vec::<Value>::new()));
        let handler_calls = Arc::new(AtomicUsize::new(0));
        client.register_task("button", {
            let edits = edits.clone();
            let handler_calls = handler_calls.clone();
            move |input: Value, ctx| {
                let edits = edits.clone();
                let handler_calls = handler_calls.clone();
                async move {
                    let feedback: ButtonFeedback = serde_json::from_value(input["feedback"].clone())?;
                    let mode = input["mode"].as_str().unwrap().to_owned();
                    let fail_processing = mode == "processing_error";
                    let fail_restore = mode == "restore_error";
                    let processing = feedback.processing.clone();
                    let original = feedback.original.clone();
                    let send = move |message: Value| {
                        let edits = edits.clone();
                        let fail = (fail_processing && message == processing)
                            || (fail_restore && message == original);
                        async move {
                            if fail {
                                return Err(WorkflowRuntimeError::Upstream("Slack edit failed".into()));
                            }
                            edits.lock().await.push(message);
                            Ok(json!({"ok": true}))
                        }
                    };
                    run(Some(feedback), &ctx.clone(), send.clone(), |feedback| async move {
                        // Deliberately not checkpointed: cosmetic failures must
                        // not cause the engine to execute this side effect again.
                        handler_calls.fetch_add(1, Ordering::SeqCst);
                        if mode == "failure" {
                            return Err(absurd::Error::InvalidOptions("handler failed".into()));
                        }
                        if !matches!(mode.as_str(), "rejection" | "restore_error") {
                            ctx.step("workflow-result", || async {
                                let message = json!({"channel": "C1", "ts": "1.1", "text": "Approved", "blocks": []});
                                let response = update(feedback.as_ref(), &ctx, &message, send(message.clone())).await;
                                if mode.ends_with("checkpoint_error") {
                                    let error: String = response.expect_err("marker write must fail");
                                    assert!(error.contains("reject_feedback_checkpoint"), "{error}");
                                    // The context RPC returned an ordinary error;
                                    // a handler can catch it and keep making calls.
                                    ctx.step("after-rpc-error", || async { Ok(()) }).await?;
                                } else {
                                    response.map_err(absurd::Error::InvalidOptions)?;
                                }
                                Ok(())
                            }).await?;
                        }
                        if mode == "failure_after_result" || mode == "failure_after_checkpoint_error" {
                            return Err(absurd::Error::InvalidOptions("later step failed".into()));
                        }
                        if mode == "replay" {
                            ctx.sleep_for("wait", Duration::from_millis(20)).await?;
                        }
                        Ok(json!({"done": true}))
                    }).await
                }
            }
        })?;
        let feedback = fixture();
        for mode in [
            "rejection",
            "failure",
            "result",
            "replay",
            "failure_after_result",
            "processing_error",
            "restore_error",
            "checkpoint_error",
            "failure_after_checkpoint_error",
            "checkpoint_read_error",
        ] {
            edits.lock().await.clear();
            handler_calls.store(0, Ordering::SeqCst);
            let params = json!({"feedback": feedback, "mode": mode});
            let spawn = client
                .spawn(
                    "button",
                    params.clone(),
                    SpawnOptions {
                        idempotency_key: Some(mode.into()),
                        max_attempts: Some(if mode == "restore_error" { 5 } else { 1 }),
                        ..Default::default()
                    },
                )
                .await?;
            if mode.ends_with("checkpoint_error") {
                // Reject a real checkpoint INSERT after Slack has accepted the
                // result. Only this task's update marker is affected.
                let task_id = uuid::Uuid::parse_str(&spawn.task_id)?;
                sqlx::query(&format!(
                    "ALTER TABLE absurd.c_{} DROP CONSTRAINT IF EXISTS reject_feedback_checkpoint,
                     ADD CONSTRAINT reject_feedback_checkpoint
                     CHECK (task_id <> '{task_id}'::uuid OR checkpoint_name <> '$slack_button.updated')",
                    client.queue_name()
                )).execute(client.pool()).await?;
            }
            if mode == "checkpoint_read_error" {
                sqlx::query(&format!(
                    "INSERT INTO absurd.c_{} (task_id, checkpoint_name, state)
                     VALUES ($1::uuid, '$slack_button.updated', $2::jsonb)",
                    client.queue_name()
                ))
                .bind(&spawn.task_id)
                .bind(json!("invalid marker"))
                .execute(client.pool())
                .await?;
            }
            client.work_batch(WorkBatchOptions::default()).await?;
            if mode == "replay" {
                tokio::time::sleep(Duration::from_millis(30)).await;
                client.work_batch(WorkBatchOptions::default()).await?;
            }
            let outcome = client
                .fetch_task_result(&spawn.task_id, None)
                .await?
                .unwrap();
            if mode.starts_with("failure") {
                assert!(
                    matches!(outcome, TaskResultSnapshot::Failed { .. }),
                    "{mode}: {outcome:?}"
                );
            } else {
                assert!(
                    matches!(outcome, TaskResultSnapshot::Completed { .. }),
                    "{mode}: {outcome:?}"
                );
                assert_eq!(
                    outcome.result::<Value>()?,
                    Some(json!({"done": true})),
                    "{mode}"
                );
            }
            let calls = if mode == "replay" { 2 } else { 1 };
            assert_eq!(handler_calls.load(Ordering::SeqCst), calls, "{mode}");
            let recorded = edits.lock().await.clone();
            let expected = match mode {
                "rejection" | "failure" => {
                    vec![feedback.processing.clone(), feedback.original.clone()]
                }
                "processing_error" | "checkpoint_read_error" => {
                    vec![json!({"channel": "C1", "ts": "1.1", "text": "Approved", "blocks": []})]
                }
                "restore_error" => vec![feedback.processing.clone()],
                _ => vec![
                    feedback.processing.clone(),
                    json!({"channel": "C1", "ts": "1.1", "text": "Approved", "blocks": []}),
                ],
            };
            assert_eq!(recorded, expected, "{mode}");
            let duplicate = client
                .spawn(
                    "button",
                    params,
                    SpawnOptions {
                        idempotency_key: Some(mode.into()),
                        ..Default::default()
                    },
                )
                .await?;
            assert!(!duplicate.created);
            assert_eq!(duplicate.task_id, spawn.task_id);
            client.work_batch(WorkBatchOptions::default()).await?;
            assert_eq!(*edits.lock().await, recorded);
            assert_eq!(handler_calls.load(Ordering::SeqCst), calls, "{mode}");
        }
        client.drop_queue(None).await?;
        Ok(())
    }
}
