//! Workflow-owned button feedback using the runner's existing checkpoints.
use absurd::{StepHandle, TaskContext};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::sync::{
    Arc,
    atomic::{AtomicBool, Ordering},
};

use crate::WorkflowRuntimeError;
use std::future::Future;

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ButtonFeedback {
    channel: String,
    ts: String,
    original: Value,
    processing: Value,
    #[serde(skip)]
    updated_step: Option<StepHandle<bool>>,
    #[serde(skip)]
    updated: Arc<AtomicBool>,
}

impl ButtonFeedback {
    /// Only render button rows generated by ctx.slack_buttons. The invocation
    /// must pass signature verification before this value is used.
    pub fn from_invocation(invocation: &crate::slack_buttons::Invocation) -> Option<Self> {
        let message = invocation.message.as_ref()?;
        let group_id = invocation.click["id"].as_str()?;
        let action = invocation.click["action"].as_str()?;
        let channel = invocation.click["channel_id"].as_str()?;
        let ts = invocation.click["message_ts"].as_str()?;
        let prefix = format!("centaur.workflow.action:{group_id}:");
        let action_id = format!("{prefix}{action}");
        let blocks = message["blocks"].as_array()?;
        let mut processing_blocks = blocks.clone();
        let index = blocks.iter().position(|block| {
            block["type"] == "actions"
                && block["elements"].as_array().is_some_and(|elements| {
                    elements.iter().all(|element| {
                        element["type"] == "button"
                            && element["action_id"]
                                .as_str()
                                .is_some_and(|id| id.starts_with(&prefix))
                    }) && elements.iter().any(|element| {
                        element["action_id"] == action_id && element["value"] == invocation.button
                    })
                })
        })?;
        let selected = blocks[index]["elements"]
            .as_array()?
            .iter()
            .find(|element| element["action_id"] == action_id)?;
        let label = selected["text"]["text"].as_str()?;
        let status = format!("⏳ {label}: Processing…");
        processing_blocks[index] = json!({
            "type": "context", "elements": [{"type": "plain_text", "text": status}]
        });
        let text = message["text"].as_str().unwrap_or_default();
        Some(Self {
            channel: channel.into(),
            ts: ts.into(),
            original: json!({"channel": channel, "ts": ts, "text": text, "blocks": blocks}),
            updated_step: None,
            updated: Arc::default(),
            processing: json!({"channel": channel, "ts": ts,
                "text": format!("{text}\n{status}"), "blocks": processing_blocks}),
        })
    }
}

impl ButtonFeedback {
    pub(crate) async fn prepare<F, Fut>(&mut self, ctx: &TaskContext, send: F) -> absurd::Result<()>
    where
        F: Fn(Value) -> Fut + Send + Sync,
        Fut: Future<Output = Result<Value, WorkflowRuntimeError>> + Send,
    {
        let updated = ctx.begin_step::<bool>("$slack_button.updated").await?;
        self.updated.store(updated.done, Ordering::SeqCst);
        self.updated_step = Some(updated);
        if !self.updated.load(Ordering::SeqCst) {
            ctx.step(
                &format!("$slack_button.processing:{}", ctx.attempt()),
                || async {
                    send(self.processing.clone())
                        .await
                        .map_err(crate::absurd_error)
                },
            )
            .await?;
        }
        Ok(())
    }

    pub(crate) async fn message_updated(
        &self,
        ctx: &TaskContext,
        message: &Value,
    ) -> Result<(), WorkflowRuntimeError> {
        if message["channel"] == self.channel
            && message["ts"] == self.ts
            && let Some(step) = &self.updated_step
        {
            ctx.complete_step(step.clone(), true).await?;
            self.updated.store(true, Ordering::SeqCst);
        }
        Ok(())
    }

    pub(crate) async fn restore_if_unhandled<F, Fut>(
        &self,
        ctx: &TaskContext,
        send: F,
    ) -> absurd::Result<()>
    where
        F: Fn(Value) -> Fut + Send + Sync,
        Fut: Future<Output = Result<Value, WorkflowRuntimeError>> + Send,
    {
        if !self.updated.load(Ordering::SeqCst) {
            ctx.step(
                &format!("$slack_button.restore:{}", ctx.attempt()),
                || async {
                    send(self.original.clone())
                        .await
                        .map_err(crate::absurd_error)
                },
            )
            .await?;
        }
        Ok(())
    }
}

/// Keep feedback in the workflow's ordered execution, including retry/replay.
pub(crate) async fn run<T, S, SF, H, HF>(
    mut feedback: Option<ButtonFeedback>,
    ctx: &TaskContext,
    send: S,
    handler: H,
) -> absurd::Result<T>
where
    S: Fn(Value) -> SF + Clone + Send + Sync,
    SF: Future<Output = Result<Value, WorkflowRuntimeError>> + Send,
    H: FnOnce(Option<ButtonFeedback>) -> HF,
    HF: Future<Output = absurd::Result<T>>,
{
    let preparation = if let Some(feedback) = &mut feedback {
        feedback.prepare(ctx, send.clone()).await
    } else {
        Ok(())
    };
    let result = match preparation {
        Ok(()) => handler(feedback.clone()).await,
        Err(error) => Err(error),
    };
    // Suspension still means work in progress. On rejection/failure, restore
    // only our own busy state; an explicit workflow edit owns the result.
    if !matches!(&result, Err(absurd::Error::Suspend))
        && let Some(feedback) = feedback
        && let Err(error) = feedback.restore_if_unhandled(ctx, send).await
    {
        tracing::warn!(%error, "failed to restore workflow buttons");
        if result.is_ok() {
            return Err(error);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use absurd::{Client, ClientOptions, SpawnOptions, TaskResultSnapshot, WorkBatchOptions};
    use std::time::Duration;
    use tokio::sync::Mutex;

    fn fixture() -> ButtonFeedback {
        let id = "00000000-0000-0000-0000-000000000001";
        let mut message = json!({"channel": "C1", "text": "Approve release?", "blocks": [
            {"type": "section", "text": {"type": "mrkdwn", "text": "Approve release?"}},
            {"type": "actions", "elements": (["approve", "reject"].map(|action| json!({
                "type": "button", "text": {"type": "plain_text", "text": action},
                "action_id": format!("centaur.workflow.action:{id}:{action}"),
                "value": json!({"workflow_name": "review", "input": {}}).to_string()
            })))}
        ]});
        crate::slack_buttons::sign_message(&mut message, b"fixture-key").unwrap();
        let invocation = crate::slack_buttons::Invocation {
            button: message["blocks"][1]["elements"][0]["value"]
                .as_str()
                .unwrap()
                .into(),
            click: json!({"id": id, "action": "approve", "channel_id": "C1", "message_ts": "1.1"}),
            idempotency_key: "click-1".into(),
            message: Some(message),
        };
        ButtonFeedback::from_invocation(&invocation).unwrap()
    }

    #[test]
    fn busy_state_replaces_the_button_row_and_preserves_the_message() {
        let feedback = fixture();
        assert_eq!(
            feedback.processing["blocks"][0],
            feedback.original["blocks"][0]
        );
        assert_eq!(
            feedback.processing["blocks"][1],
            json!({"type": "context", "elements": [
                {"type": "plain_text", "text": "⏳ approve: Processing…"}
            ]})
        );
        assert_eq!(
            feedback.processing["text"],
            "Approve release?\n⏳ approve: Processing…"
        );
        assert_eq!(
            feedback.original["blocks"][1]["elements"]
                .as_array()
                .unwrap()
                .len(),
            2
        );
    }

    #[tokio::test]
    async fn durable_feedback_restores_rejection_and_failure_and_preserves_results_on_replay()
    -> Result<(), Box<dyn std::error::Error>> {
        let Ok(url) = std::env::var("ABSURD_TEST_DATABASE_URL") else {
            return Ok(());
        };
        let pool = sqlx::PgPool::connect(&url).await?;
        let installed: bool = sqlx::query_scalar(
            "SELECT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'absurd')",
        )
        .fetch_one(&pool)
        .await?;
        if !installed {
            sqlx::raw_sql(include_str!(
                "../../centaur-session-sqlx/migrations/0007_absurd_workflows.sql"
            ))
            .execute(&pool)
            .await?;
        }
        let client = Client::from_pool_with_options(
            pool,
            ClientOptions {
                queue_name: format!("button_{}", uuid::Uuid::new_v4().simple()),
                ..Default::default()
            },
        )?;
        client.create_queue(None, Default::default()).await?;
        let edits = Arc::new(Mutex::new(Vec::<Value>::new()));
        client.register_task("button", {
            let edits = edits.clone();
            move |input: Value, ctx| {
                let edits = edits.clone();
                async move {
                    let feedback: ButtonFeedback = serde_json::from_value(input["feedback"].clone())?;
                    let send = move |message: Value| {
                        let edits = edits.clone();
                        async move { edits.lock().await.push(message); Ok(json!({"ok": true})) }
                    };
                    run(Some(feedback), &ctx.clone(), send.clone(), |feedback| async move {
                        let mode = input["mode"].as_str().unwrap();
                        if mode == "failure" { return Err(absurd::Error::InvalidOptions("handler failed".into())); }
                        if mode == "result" || mode == "replay" || mode == "failure_after_result" {
                            ctx.step("workflow-result", || async {
                                let message = json!({"channel": "C1", "ts": "1.1", "text": "Approved", "blocks": []});
                                send(message.clone()).await.map_err(crate::absurd_error)?;
                                feedback.as_ref().unwrap().message_updated(&ctx, &message).await.map_err(crate::absurd_error)?;
                                Ok(())
                            }).await?;
                        }
                        if mode == "failure_after_result" {
                            return Err(absurd::Error::InvalidOptions("later step failed".into()));
                        }
                        if mode == "replay" { ctx.sleep_for("wait", Duration::from_millis(20)).await?; }
                        Ok(json!({"done": true}))
                    }).await
                }
            }
        })?;
        let feedback = fixture();
        for mode in [
            "rejection",
            "failure",
            "result",
            "replay",
            "failure_after_result",
        ] {
            edits.lock().await.clear();
            let params = json!({"feedback": feedback, "mode": mode});
            let spawn = client
                .spawn(
                    "button",
                    params.clone(),
                    SpawnOptions {
                        idempotency_key: Some(mode.into()),
                        max_attempts: Some(1),
                        ..Default::default()
                    },
                )
                .await?;
            client.work_batch(WorkBatchOptions::default()).await?;
            if mode == "replay" {
                tokio::time::sleep(Duration::from_millis(30)).await;
                client.work_batch(WorkBatchOptions::default()).await?;
            }
            let outcome = client
                .fetch_task_result(&spawn.task_id, None)
                .await?
                .unwrap();
            if mode.starts_with("failure") {
                assert!(
                    matches!(outcome, TaskResultSnapshot::Failed { .. }),
                    "{mode}: {outcome:?}"
                );
            } else {
                assert!(
                    matches!(outcome, TaskResultSnapshot::Completed { .. }),
                    "{mode}: {outcome:?}"
                );
            }
            let recorded = edits.lock().await.clone();
            assert_eq!(recorded.len(), 2, "{mode}: {recorded:?}");
            assert_eq!(recorded[0], feedback.processing, "{mode}");
            if mode == "rejection" || mode == "failure" {
                assert_eq!(recorded[1], feedback.original, "{mode}");
            } else {
                assert_eq!(recorded[1]["text"], "Approved", "{mode}");
                assert_eq!(recorded[1]["blocks"], json!([]), "{mode}");
            }
            let duplicate = client
                .spawn(
                    "button",
                    params,
                    SpawnOptions {
                        idempotency_key: Some(mode.into()),
                        ..Default::default()
                    },
                )
                .await?;
            assert!(!duplicate.created);
            assert_eq!(duplicate.task_id, spawn.task_id);
            client.work_batch(WorkBatchOptions::default()).await?;
            assert_eq!(*edits.lock().await, recorded);
        }
        client.drop_queue(None).await?;
        Ok(())
    }
}
