//! Workflow-owned button feedback using the runner's existing checkpoints.
use std::{
    future::Future,
    sync::{
        Arc,
        atomic::{AtomicBool, Ordering},
    },
};

use absurd::{StepHandle, TaskContext};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

use crate::WorkflowRuntimeError;

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ButtonFeedback {
    original: Value,
    processing: Value,
    #[serde(skip)]
    attempt: Option<Arc<FeedbackAttempt>>,
}

/// Shared only within an attempt. The checkpoint preserves ownership on replay.
#[derive(Debug)]
struct FeedbackAttempt {
    update_checkpoint: StepHandle<bool>,
    message_replaced: AtomicBool,
}

impl FeedbackAttempt {
    fn new(update_checkpoint: StepHandle<bool>) -> Self {
        Self {
            message_replaced: AtomicBool::new(update_checkpoint.done),
            update_checkpoint,
        }
    }
}

impl ButtonFeedback {
    fn needs_feedback(&self) -> bool {
        self.attempt
            .as_ref()
            .is_some_and(|attempt| !attempt.message_replaced.load(Ordering::SeqCst))
    }

    /// Only render button rows generated by ctx.slack_buttons. The invocation
    /// must pass signature verification before this value is used.
    pub fn from_invocation(invocation: &crate::slack_buttons::Invocation) -> Option<Self> {
        let message = invocation.message.as_ref()?;
        let group_id = invocation.click["id"].as_str()?;
        let action = invocation.click["action"].as_str()?;
        let channel = invocation.click["channel_id"].as_str()?;
        let ts = invocation.click["message_ts"].as_str()?;
        let prefix = format!("centaur.workflow.action:{group_id}:");
        let action_id = format!("{prefix}{action}");
        let blocks = message["blocks"].as_array()?;
        let (index, selected) = blocks.iter().enumerate().find_map(|(index, block)| {
            selected_workflow_button(block, &prefix, &action_id, &invocation.button)
                .map(|button| (index, button))
        })?;
        let mut processing_blocks = blocks.clone();
        let label = selected["text"]["text"].as_str()?;
        let status = format!("⏳ {label}: Processing…");
        processing_blocks[index] = json!({
            "type": "context", "elements": [{"type": "plain_text", "text": status}]
        });
        let text = message["text"].as_str().unwrap_or_default();
        Some(Self {
            original: json!({"channel": channel, "ts": ts, "text": text, "blocks": blocks}),
            attempt: None,
            processing: json!({"channel": channel, "ts": ts,
                "text": format!("{text}\n{status}"), "blocks": processing_blocks}),
        })
    }
}

fn selected_workflow_button<'a>(
    block: &'a Value,
    group_prefix: &str,
    action_id: &str,
    signed_value: &str,
) -> Option<&'a Value> {
    if block["type"] != "actions" {
        return None;
    }
    let buttons = block["elements"].as_array()?;
    let belongs_to_group = |button: &Value| {
        button["type"] == "button"
            && button["action_id"]
                .as_str()
                .is_some_and(|id| id.starts_with(group_prefix))
    };
    if !buttons.iter().all(belongs_to_group) {
        return None;
    }
    buttons
        .iter()
        .find(|button| button["action_id"] == action_id && button["value"] == signed_value)
}

/// Report update errors through the context RPC without losing a successful Slack edit.
pub(crate) async fn update(
    feedback: Option<&ButtonFeedback>,
    ctx: &TaskContext,
    message: &Value,
    response: impl Future<Output = Result<Value, WorkflowRuntimeError>>,
) -> Result<Value, String> {
    let value = response.await.map_err(|error| error.to_string())?;
    if let Some(feedback) = feedback
        && message["channel"] == feedback.original["channel"]
        && message["ts"] == feedback.original["ts"]
        && let Some(attempt) = &feedback.attempt
    {
        // Slack already changed. A checkpoint error must never let cleanup
        // overwrite that result, even when Python does not catch the RPC error.
        attempt.message_replaced.store(true, Ordering::SeqCst);
        ctx.complete_step(attempt.update_checkpoint.clone(), true)
            .await
            .map_err(|error| error.to_string())?;
    }
    Ok(value)
}

/// Keep feedback in the workflow's ordered execution, including retry/replay.
pub(crate) async fn run<T, SendFuture, HandlerFuture>(
    mut feedback: Option<ButtonFeedback>,
    ctx: &TaskContext,
    send: impl Fn(Value) -> SendFuture + Send + Sync,
    handler: impl FnOnce(Option<ButtonFeedback>) -> HandlerFuture,
) -> absurd::Result<T>
where
    SendFuture: Future<Output = Result<Value, WorkflowRuntimeError>> + Send,
    HandlerFuture: Future<Output = absurd::Result<T>>,
{
    if let Some(feedback) = &mut feedback {
        match ctx.begin_step::<bool>("$slack_button.updated").await {
            Ok(checkpoint) => feedback.attempt = Some(Arc::new(FeedbackAttempt::new(checkpoint))),
            Err(error) => {
                feedback.attempt = None;
                tracing::warn!(%error, "failed to read workflow button feedback checkpoint")
            }
        }
    }
    // If the checkpoint cannot be read, leave the display alone. The handler
    // still runs, but we cannot safely replace a result from an earlier attempt.
    let feedback = feedback.filter(|feedback| feedback.attempt.is_some());
    if let Some(feedback) = &feedback
        && feedback.needs_feedback()
    {
        let processing = ctx
            .step(
                &format!("$slack_button.processing:{}", ctx.attempt()),
                || async {
                    send(feedback.processing.clone())
                        .await
                        .map_err(crate::absurd_error)
                },
            )
            .await;
        if let Err(error) = processing {
            tracing::warn!(%error, "failed to show workflow button processing state");
        }
    }
    let result = handler(feedback.clone()).await;
    // Suspension still means work in progress. On rejection/failure, restore
    // only our own busy state; an explicit workflow edit owns the result.
    if !matches!(&result, Err(absurd::Error::Suspend))
        && let Some(feedback) = feedback
        && feedback.needs_feedback()
    {
        let restored = ctx
            .step(
                &format!("$slack_button.restore:{}", ctx.attempt()),
                || async {
                    send(feedback.original.clone())
                        .await
                        .map_err(crate::absurd_error)
                },
            )
            .await;
        if let Err(error) = restored {
            tracing::warn!(%error, "failed to restore workflow buttons");
        }
    }
    result
}

#[cfg(test)]
mod tests;
