name: Console Gem Audit

on:
  push:
    branches: [ main ]

permissions:
  contents: read

defaults:
  run:
    working-directory: services/console

jobs:
  scan_gems:
    runs-on: depot-ubuntu-24.04-16

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@e8944e80fb94b20106697132f8c20c665fab29e9 # v1.325.0
        with:
          working-directory: services/console
          bundler-cache: true

      - name: Scan for known security vulnerabilities in gems used
        run: bin/bundler-audit
